@startuml
title Benutzerrolle ändern

!theme plain
skinparam linetype ortho
start

:<back:White>"/service/account-management" aufrufen;
:<back:LightBlue>Nutzer über Liste oder Suche auswählen;
:<back:LightBlue>Detailmodal öffnet sich;
:<back:LightGreen>"Rolle anpassen" wählen;
:<back:LightGreen>Neue Rolle im Dropdown setzen;
:<back:LightGreen>"Speichern" klicken;
:<back:White>System aktualisiert Rolle des Users;

stop
@enduml
