@startuml
title Profildaten bearbeiten

!theme plain
skinparam linetype ortho
start

:<back:White>"/profile" aufrufen;
:<back:LightBlue>Bereich "Meine Daten" -> Stiftsymbol anklicken;
:<back:LightGreen>Felder bearbeiten (Name, Adresse, Telefon ...);
:<back:LightBlue>"Speichern" drücken;
:<back:LightGreen>System aktualisiert die Daten;

stop
@enduml
