@startuml
title Registration Process

!theme plain
skinparam linetype ortho
start

:<back:White>Öffne "/login";
if (Neuer Kunde?) then (ja)
:<back:White>Weiterleitung auf "/register";
:<back:LightGreen>Registrierungs-Formular öffnen & ausfüllen;
  if (Behindertenausweis vorhanden?) then (ja)
    :<back:LightGreen>Ausweis aktivieren & Fotos hochladen;
    else (nein)
    :<back:LightGreen>Registrierung ohne Ausweis;
  endif
  :<back:LightGreen>Formular abschicken;
  :<back:White>Weiterleitung auf "/login";
else (nein)
  :<back:LightBlue>E-Mail & Passwort eingeben & abschicken;
endif

if (Anmeldedaten korrekt?) then (ja)
  :Weiterleitung zur Startseite;
else (nein)
  :Fehlermeldung anzeigen;
endif

stop
@enduml
